---
Assignment: Assignment 1.2
author: "Zachary DeNoto"
date: "September 10th 2020"
output: pdf_document
---


```{r}
library(readxl)
data <- read_excel('obama-approval-ratings.xls')
data
```

```{r}
library(grid)
library(gridBase)
data_subset = data[which(data$Approve >44),]
barplot(names.arg =  data_subset$Issue, height =  data_subset$Approve, col = rainbow(4), main = 'Approval Ratings for Obama by Policy', xlab = 'Policy', ylab = 'Approval Rating (%)' )

```





```{r}
library(ggplot2)
library(NLP)


hotdog_winner <- read_excel('hotdog-contest-winners.xlsm')
hotdog_winner
hotdog_winner <- hotdog_winner[which(hotdog_winner$`Dogs eaten`>20.0),]



dogs <- hotdog_winner$`Dogs eaten`
country <- hotdog_winner$Country

ggplot(hotdog_winner, aes(fill = Winner, y = dogs, x = country)) + geom_bar(position = 'stack', stat = 'identity') + labs( x = 'Country', y = 'Number of hot dogs eaten', title = 'Number of hot dogs eaten by country for hot dog eating winners')



```






```{r}
library(plotly)

obama <- read_excel('obama-approval-ratings.xls')

obama1 <- obama[1,]
obama1

labels <- names(obama1[2:4])

obama1 <- obama1[2:4]
values <- c(obama1[[1]],obama1[[2]],obama1[[3]])

pie <- plot_ly(type = 'pie', labels = labels, values = values, textinfo = 'label+percent')

pie <- pie %>% layout(title = "Obama's Approval Ratings on Race Relations",  showlegend = F,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

pie


```



```{r}


obama2 <- obama[2,]

obama2
labels <- names(obama2[2:4])

obama2 <- obama2[2:4]
values <- c(obama2[[1]],obama2[[2]],obama2[[3]])


pie <- plot_ly( labels = labels, values = values, sort = FALSE,textinfo='label+percent')

pie <- pie %>% add_pie(hole = 0.6, col = 'white')

pie <- pie %>% layout(title = "Obama's Approval Ratings on Education",  showlegend = F,
                      xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
                      yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))



pie


```

