---
Assignment: Assignment 4.2
author: "Zachary DeNoto"
date: "October 15th 2020"
output: pdf_document
---


```{r}
library(readxl)


data <- read.csv('birth-rate.csv')
data
```



```{r}
library(ggplot2)
library(dplyr)

x <- data[which(data$X1960 <16),]




ggplot(data = x, aes(y= x$X1960, x = x$Country)) +
  geom_point(fill = 'blue')+
  labs(x = 'Year', y = 'Birth Rate')+
  ggtitle('Birth Rate of 1960 by Country')
```

```{r}
library(plotly)


#data <- read.delim('tv_sizes.txt')
#data

#data <- data[which(data$year ==2008),]

x <- data[which(data$X1960 <28),]
x <- x[which(x$X1980 <30),]

fig <- plot_ly(x, x = ~X1960, y = ~X1980, type = 'scatter', mode = 'markers',
        marker = list(size = ~X1980, opacity = 0.5))
fig <- fig %>% layout(title = 'Birth Rate in 1960 compared to 1980',
         xaxis = list(showgrid = FALSE),
         yaxis = list(showgrid = FALSE))

fig
```



```{r}


data <- read.delim('tv_sizes.txt')
#data

data['year'] <-  sapply(data['year'], as.character) 

data <- data[which(data$size <60),]
data <- data[which(data$year <2005),]


p <- ggplot(data, aes(size, fill = year)) + geom_density(alpha = 0.2) +
  ggtitle('Density of TV Sizes')

fig <- ggplotly(p)

fig



```









